In [13]:
import os
import pickle

def load_model(file):
    """
    Read .pickle file
    """
    path_to_pickle = os.path.join(os.getcwd(), file)
    try:
        with open(path_to_pickle, 'rb') as handle:
            model = pickle.load(handle)
    except pickle.UnpicklingError as error:
        raise Exception(error)
    else:
        return model

def save_model(file, model):
    """
    The pickle module implements binary protocols
    for serializing and de-serializing a Python object structure.
    """
    #path_to_pickle = os.path.join(os.getcwd(), file)
    path_to_pickle = file
    try:
        #FileHelper.create_folder(FileHelper.get_folder_path(path_to_pickle))
        with open(path_to_pickle, 'wb') as handle:
            pickle.dump(model, handle, protocol=pickle.HIGHEST_PROTOCOL)
    except pickle.PickleError as error:
        raise Exception(error)
    else:
        return True
    
file = 'itu_model.pickle'
modle = "{'bootstrap': True, 'max_depth': 6, 'max_features': 2, 'min_samples_leaf': 4, 'min_samples_split': 3, 'n_estimators': 200}"
model = save_model(file, modle)

In [8]:
data = pd.read_csv(r"/Volumes/D/py-workspace/PFE/dataset/Input/outband_QoS_ITU-QoE.csv", nrows=20000)
#data = pd.read_csv(r"/Volumes/D/py-workspace/PFE/dataset/Input/outband_QoS_ITU-QoE.csv")
data = data.dropna()

display(data.shape)

data.to_csv('20000_outband_QoS_ITU-QoE.csv')

# import numpy as np
# import pandas as pd

# y = np.array([-0.33749783, -0.33404952, -0.32520722, -0.33489578, -0.33121301,
#        -0.33966687, -0.32596874, -0.32584136, -0.32636478, -0.3359489 ])

# 1000_
array([-0.3190114 , -0.36423656, -0.35432759, -0.43027544, -0.30940877,
       -0.31271521, -0.33856421, -0.36408426, -0.40078015, -0.33609019])

## Azure 20000
array([-0.33749542, -0.33405209, -0.32520944, -0.33489759, -0.33121085,
       -0.33966586, -0.32597416, -0.32584195, -0.32636342, -0.33594622])


Records = 20000
max-depth 6
max-n_estimators 1000
array([-0.33749542, -0.33405209, -0.32520944, -0.33489759, -0.33121085,
       -0.33966586, -0.32597416, -0.32584195, -0.32636342, -0.33594622])

# df1 = pd.DataFrame(y) 
# #df = pd.DataFrame(predictions)



# display(df1)
# df1.to_csv('itu_neg_mse.csv')

(20000, 6)